### ISSUE TITLE
Index regeneration on delete doesn't work

### ISSUE THREAD

**Issue by akushsky** [helm/chartmuseum#365]
When I try to delete a chart

`curl -XDELETE http://192.168.1.1:8080/api/charts/mychart/1.2.3`

It always returns `{"deleted":true}`, deletes file from the storage, but in index-cache.yaml it only changes the generation time, without removing entry with deleted chart version. That's really an unexpected behavior.

My chartmuseum version is 0.12.0 (build 101e26a) and I use S3 as backend storage.

**Comment by scbizu** [comment]
Duplicate #22 and #220 ?

**Comment by akushsky** [comment]
> Duplicate #22 and #220 ?

Totally agree.
We have version system like "10.0.2-112" and could reproduce that issue.

Is there at least workaround for now?

**Comment by scbizu** [comment]
> > Duplicate #22 and #220 ?
> 
> Totally agree.
> We have version system like "10.0.2-112" and could reproduce that issue.
> 
> Is there at least workaround for now?

I have fixed it at #362 , and still waiting @jdolitsky for some reviewing . For now , you should avoid this kind of version number until the patch merge into master and spawn the new release.

**Comment by pixelicous** [comment]
Still encounter this problem, new chart museum version and deployment
